#!/usr/bin/env bun
/**
 * Emits `src/generated/error-retryability.gen.ts` from the vendored spec.
 *
 * sumvin-api publishes one retryability answer per error code as the
 * `x-retryable` extension on the `APIErrorCode` schema (code -> boolean).
 * hey-api does not carry `x-` extensions into its output, so this step turns
 * that map into a typed constant. Runs after `openapi-ts` in `bun run
 * generate`, since hey-api owns (and rewrites) the `src/generated` tree.
 *
 * Fails, writing nothing, when the extension is missing or does not give a
 * boolean for exactly the schema's enum values — a code without an answer is
 * a spec defect to fix upstream, never something to default here.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const SPEC_PATH = 'spec/openapi.json';
const OUTPUT_PATH = 'src/generated/error-retryability.gen.ts';

interface ErrorCodeSchema {
  enum?: unknown;
  'x-retryable'?: unknown;
}

function readRetryability(): Array<[string, boolean]> {
  const spec = JSON.parse(readFileSync(SPEC_PATH, 'utf-8')) as {
    components?: { schemas?: Record<string, ErrorCodeSchema> };
  };
  const schema = spec.components?.schemas?.APIErrorCode;
  if (schema === undefined || !Array.isArray(schema.enum)) {
    throw new Error('spec has no APIErrorCode enum schema');
  }
  const published = schema['x-retryable'];
  if (published === null || typeof published !== 'object' || Array.isArray(published)) {
    throw new Error('APIErrorCode schema carries no x-retryable map');
  }
  const flags = published as Record<string, unknown>;
  const codes = schema.enum as string[];

  const missing = codes.filter((code) => typeof flags[code] !== 'boolean');
  const unknown = Object.keys(flags).filter((code) => !codes.includes(code));
  if (missing.length > 0 || unknown.length > 0) {
    throw new Error(
      `x-retryable does not match the APIErrorCode enum — missing or non-boolean: [${missing.join(', ')}]; not in enum: [${unknown.join(', ')}]`,
    );
  }
  return [...codes].sort().map((code) => [code, flags[code] as boolean]);
}

function render(entries: Array<[string, boolean]>): string {
  const lines = entries.map(([code, retryable]) => `  '${code}': ${retryable},`);
  return [
    '// This file is auto-generated by scripts/generate-error-retryability.ts from spec/openapi.json',
    '',
    "import type { ApiErrorCode } from './types.gen';",
    '',
    '/**',
    ' * Whether an identical retry of a request that failed with this error code,',
    ' * after a short backoff, can succeed — as published by the API on each code.',
    ' */',
    'export const apiErrorCodeRetryable = {',
    ...lines,
    '} as const satisfies Readonly<Record<ApiErrorCode, boolean>>;',
    '',
  ].join('\n');
}

try {
  const entries = readRetryability();
  writeFileSync(OUTPUT_PATH, render(entries));
  const retryable = entries.filter(([, flag]) => flag).length;
  console.info(`Wrote ${OUTPUT_PATH}: ${entries.length} codes, ${retryable} retryable.`);
} catch (error) {
  console.error('generate-error-retryability failed:', (error as Error).message);
  process.exit(1);
}
